service: handle-csv

provider:
  name: aws
  runtime: python3.8
  credentials:
    accessKeyId: ###
    secretAccessKey: ###--

package:
  exclude:
      - node_modules/**
      - venv/**

functions:
  handle-csv:
    handler: handler.main

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true